-- Completa catálogo de fuentes e indicadores para ejecución ETL total
-- sobre bases existentes, sin borrar datos.

INSERT INTO public.fuentes_datos
    (id, nombre, url_referencia, periodicidad, modulo_etl, estado, activo)
VALUES
    (1,  'INEGI BIE — PIB Trimestral a precios corrientes (MXN)', 'https://www.inegi.org.mx/', 'mensual',    'sources.inegi.pib_trimestral',             'etl_listo', TRUE),
    (2,  'Banxico — Tipo de Cambio USD/MXN (FIX)',                'https://www.banxico.org.mx/', 'diario',     'sources.banxico.tipo_cambio',              'etl_listo', TRUE),
    (3,  'Banxico — Inflación INPC (variación anual %)',          'https://www.banxico.org.mx/', 'mensual',    'sources.banxico.inflacion',                'etl_listo', TRUE),
    (4,  'INEGI BISE — Población total nacional',                 'https://www.inegi.org.mx/',   'quinquenal', 'sources.inegi.poblacion_nacional',         'etl_listo', TRUE),
    (5,  'INEGI — Grupos de edad nacional',                       'https://www.inegi.org.mx/',   'quinquenal', 'sources.inegi.grupos_edad_nacional',       'etl_listo', TRUE),
    (6,  'INEGI BISE — Población por sexo nacional',              'https://www.inegi.org.mx/',   'quinquenal', 'sources.inegi.poblacion_sexo_nacional',    'etl_listo', TRUE),
    (7,  'INEGI — PEA nacional',                                  'https://www.inegi.org.mx/',   'mensual',    'sources.inegi.pea_nacional',               'etl_listo', TRUE),
    (8,  'INEGI — Ocupación por sector nacional',                 'https://www.inegi.org.mx/',   'mensual',    'sources.inegi.ocupacion_sector_nacional',  'etl_listo', TRUE),
    (9,  'World Bank — PIB anual MXN',                            'https://data.worldbank.org/', 'anual',      'sources.worldbank.pib_anual',              'etl_listo', TRUE),
    (10, 'IMF — Proyección PIB',                                  'https://www.imf.org/',        'anual',      'sources.imf.pib_proyeccion',               'etl_listo', TRUE),
    (11, 'SE — IED por sector',                                   'https://www.gob.mx/se',       'anual',      'sources.se.ied_sector',                    'etl_listo', TRUE),
    (12, 'SE — IED por país',                                     'https://www.gob.mx/se',       'anual',      'sources.se.ied_pais',                      'etl_listo', TRUE),
    (13, 'World Bank — Ingresos por turismo',                     'https://data.worldbank.org/', 'anual',      'sources.worldbank.turismo_ingresos',       'etl_listo', TRUE),
    (14, 'World Bank — Ranking turismo',                          'https://data.worldbank.org/', 'anual',      'sources.worldbank.turismo_ranking',        'etl_listo', TRUE),
    (15, 'INEGI — Balanza de visitantes',                         'https://www.inegi.org.mx/',   'anual',      'sources.inegi.balanza_visitantes',         'etl_listo', TRUE),
    (16, 'AFAC — Mercado aéreo',                                  'https://www.gob.mx/afac',     'anual',      'sources.afac.mercado_aereo',               'etl_listo', TRUE),
    (17, 'SE — Anuncios de inversión',                            'https://www.gob.mx/se',       'anual',      'sources.se.anuncios_inversion',            'etl_listo', TRUE),
    (18, 'SE — Anuncios de inversión base',                       'https://www.gob.mx/se',       'anual',      'sources.se.anuncios_base',                 'etl_listo', TRUE),
    (19, 'INEGI/DataMexico — PIB por sector',                     'https://www.inegi.org.mx/',   'anual',      'sources.inegi.pib_sector',                 'etl_listo', TRUE),
    (20, 'INEGI/DataMexico — Balanza comercial',                  'https://www.inegi.org.mx/',   'anual',      'sources.inegi.balanza_comercial',          'etl_listo', TRUE),
    (21, 'AFAC — Operaciones aeroportuarias',                     'https://www.gob.mx/afac',     'anual',      'sources.afac.operaciones_aeroportuarias',  'etl_listo', TRUE),
    (22, 'INEGI/DataMexico — Actividad hotelera',                 'https://www.inegi.org.mx/',   'anual',      'sources.inegi.actividad_hotelera',         'etl_listo', TRUE),
    (23, 'SE — IED por estados',                                  'https://www.gob.mx/se',       'anual',      'sources.se.ied_estados',                   'etl_listo', TRUE),
    (24, 'INEGI — Estados info (PIB/Población/Extensión)',        'https://www.inegi.org.mx/',   'anual',      'sources.inegi.estados_info',               'etl_listo', TRUE),
    (25, 'INEGI — Demografía estatal',                            'https://www.inegi.org.mx/',   'anual',      'sources.inegi.demografia_estatal',         'etl_listo', TRUE),
    (26, 'CONAPO — Proyecciones estatales',                       'https://www.gob.mx/conapo',   'anual',      'sources.conapo.proyecciones_estatal',      'etl_listo', TRUE),
    (27, 'INEGI — ITAEE estatal',                                 'https://www.inegi.org.mx/',   'anual',      'sources.inegi.itaee_estatal',              'etl_listo', TRUE),
    (28, 'SE/DataMexico — Anuncios estatal',                      'https://www.gob.mx/se',       'anual',      'sources.se.anuncios_estatal',              'etl_listo', TRUE),
    (29, 'Datatur/SECTUR — Actividad hotelera estatal',           'https://www.datatur.sectur.gob.mx/', 'mensual', 'sources.sectur.hotelera_estatal', 'etl_listo', TRUE),
    (30, 'Datatur/SECTUR — Llegada de turistas estatal',          'https://www.datatur.sectur.gob.mx/', 'anual',   'sources.sectur.llegada_turistas_estatal', 'etl_listo', TRUE),
    (31, 'SE/DataMéxico — Exportaciones por estado',              'https://www.economia.gob.mx/datamexico/', 'anual', 'sources.se.exportaciones_estatal', 'etl_listo', TRUE),
    (32, 'DGAC/AFAC — Aeropuertos por estado',                    'https://www.gob.mx/afac', 'anual', 'sources.afac.aeropuertos_estatal', 'etl_listo', TRUE),
    (33, 'CONAPO — Población municipal por sexo',                 'https://www.gob.mx/conapo', 'anual', 'sources.conapo.municipios_poblacion', 'etl_listo', TRUE),
    (34, 'CONAPO — Pirámide municipal por edad y sexo',           'https://www.gob.mx/conapo', 'anual', 'sources.conapo.municipios_piramide_edad', 'etl_listo', TRUE),
    (35, 'CONAPO — Proyección poblacional municipal',             'https://www.gob.mx/conapo', 'anual', 'sources.conapo.municipios_proyeccion', 'etl_listo', TRUE),
    (36, 'CONAPO — Población por localidad',                      'https://www.gob.mx/conapo', 'anual', 'sources.conapo.localidades_poblacion', 'etl_listo', TRUE),
    (37, 'CONAPO — Pirámide de población por localidad',          'https://www.gob.mx/conapo', 'anual', 'sources.conapo.localidades_piramide_edad', 'etl_listo', TRUE),
    (38, 'Observatur Yucatán / ENOE-INEGI — Ocupación en restaurantes y hoteles (Mérida)', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.inegi.ocupacion_restaurantes_hoteles_yucatan', 'etl_listo', TRUE),
    (39, 'DataMéxico — Comercio internacional de Mérida', 'https://www.economia.gob.mx/datamexico/es/profile/geo/merida-993101', 'anual', 'sources.se.comercio_internacional_merida', 'etl_listo', TRUE),
    (40, 'AFAC — Conectividad aérea de Mérida', 'https://www.gob.mx/afac/acciones-y-programas/estadisticas-280404', 'anual', 'sources.afac.conectividad_aerea_merida', 'etl_listo', TRUE),
    (41, 'datos.gob.mx/AFAC — Conexiones aéreas hacia Mérida', 'https://www.datos.gob.mx/dataset/movimiento_operacional_aicm', 'anual', 'sources.afac.conexiones_aereas_merida', 'etl_listo', TRUE),
    (42, 'datos.gob.mx — Oferta de servicios turísticos en Mérida', 'https://www.datos.gob.mx/dataset/servicios_turisticos/resource/e1fcea3e-773f-4b2a-a692-c13edbe00b8f', 'anual', 'sources.sectur.oferta_servicios_turisticos_merida', 'etl_listo', TRUE),
    (43, 'Observatur Yucatán — Ocupación hotelera promedio en Mérida', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.ocupacion_hotelera_promedio_merida', 'etl_listo', TRUE),
    (44, 'Observatur Yucatán — Llegada de visitantes con pernocta en Mérida', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.llegada_visitantes_pernocta_merida', 'etl_listo', TRUE),
    (45, 'Observatur Yucatán — Gasto promedio diario del visitante con pernocta en Mérida', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.gasto_promedio_diario_pernocta_merida', 'etl_listo', TRUE),
    (46, 'Observatur Yucatán — Derrama económica estimada de visitantes con pernocta en Mérida', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.derrama_economica_pernocta_merida', 'etl_listo', TRUE),
    (47, 'Observatur Yucatán — Ingreso hotelero en Mérida', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.ingreso_hotelero_merida', 'etl_listo', TRUE),
    (48, 'Observatur Yucatán — Establecimientos de servicios turísticos en Yucatán', 'https://www.observaturyucatan.org.mx/indicadores', 'anual', 'sources.sectur.establecimientos_servicios_turisticos_yucatan', 'etl_listo', TRUE),
    (49, 'SE/datos.gob.mx — Comercio internacional Monterrey (proxy IED)', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.comercio_internacional_monterrey', 'etl_listo', TRUE),
    (50, 'SE/datos.gob.mx — Exportaciones e importaciones Monterrey', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.exportaciones_importaciones_monterrey', 'etl_listo', TRUE),
    (51, 'OMA/AFAC — Llegadas de pasajeros Monterrey', 'https://www.oma.aero/', 'anual', 'sources.afac.llegadas_pasajeros_monterrey', 'etl_listo', TRUE),
    (52, 'SECTUR/Datatur — Visitantes nacionales y extranjeros Monterrey', 'https://datatur.sectur.gob.mx/', 'anual', 'sources.sectur.visitantes_nacionales_extranjeros_monterrey', 'etl_listo', TRUE),
    (53, 'SECTUR/Datatur — Ocupación hotelera Monterrey', 'https://datatur.sectur.gob.mx/', 'anual', 'sources.sectur.ocupacion_hotelera_monterrey', 'etl_listo', TRUE),
    (54, 'INEGI — PEA Querétaro (ENOE 15 años y más)', 'https://www.inegi.org.mx/programas/enoe/15ymas/#datos_abiertos', 'anual', 'sources.inegi.pea_queretaro', 'etl_listo', TRUE),
    (55, 'INEGI — Tasa de participación laboral Querétaro (ENOE 15 años y más)', 'https://www.inegi.org.mx/programas/enoe/15ymas/#tabulados', 'anual', 'sources.inegi.tasa_participacion_laboral_queretaro', 'etl_listo', TRUE),
    (56, 'INEGI — Tasa de desocupación Querétaro (ENOE 15 años y más)', 'https://www.inegi.org.mx/programas/enoe/15ymas/#tabulados', 'anual', 'sources.inegi.tasa_desocupacion_queretaro', 'etl_listo', TRUE),
    (57, 'INEGI — Composición sectorial del empleo Querétaro (ENOE 15 años y más)', 'https://www.inegi.org.mx/programas/enoe/15ymas/#tabulados', 'anual', 'sources.inegi.composicion_sectorial_empleo_queretaro', 'etl_listo', TRUE),
    (58, 'INEGI — PIB estatal total Querétaro', 'https://www.inegi.org.mx/app/tabulados/default.aspx?pr=17&vr=6&in=2&tp=20&wr=1&cno=2', 'anual', 'sources.inegi.pib_estatal_total_queretaro', 'etl_listo', TRUE),
    (59, 'INEGI — PIB per cápita Querétaro', 'https://www.inegi.org.mx/app/tabulados/default.aspx?pr=17&vr=6&in=2&tp=20&wr=1&cno=2', 'anual', 'sources.inegi.pib_per_capita_queretaro', 'etl_listo', TRUE),
    (60, 'INEGI — Distribución del PIB por sector Querétaro', 'https://www.inegi.org.mx/temas/pib/#tabulados', 'anual', 'sources.inegi.pib_sector_queretaro', 'etl_listo', TRUE),
    (61, 'INEGI — Tasa de crecimiento económico Querétaro', 'https://www.inegi.org.mx/temas/pib/#tabulados', 'anual', 'sources.inegi.tasa_crecimiento_economico_queretaro', 'etl_listo', TRUE),
    (62, 'SE/datos.gob.mx — Exportaciones estatales Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.exportaciones_estatales_queretaro', 'etl_listo', TRUE),
    (63, 'SE/datos.gob.mx — Importaciones estatales Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.importaciones_estatales_queretaro', 'etl_listo', TRUE),
    (64, 'SE/datos.gob.mx — Comercio internacional neto Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.comercio_internacional_neto_queretaro', 'etl_listo', TRUE),
    (65, 'SE/datos.gob.mx — Balance comercial neto Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.balance_comercial_neto_queretaro', 'etl_listo', TRUE),
    (66, 'SE/datos.gob.mx — IED anual Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.ied_anual_queretaro', 'etl_listo', TRUE),
    (67, 'SE/datos.gob.mx — IED por municipio Querétaro', 'https://www.datos.gob.mx/dataset/inversion_extranjera_directa', 'anual', 'sources.se.ied_municipio_queretaro', 'etl_listo', TRUE),
    (68, 'INEGI — Llegada total de turistas Querétaro', 'https://www.inegi.org.mx/temas/turismo/#tabulados', 'anual', 'sources.inegi.llegada_total_turistas_queretaro', 'etl_listo', TRUE),
    (69, 'Datatur/Sectur — Turismo nacional vs internacional Querétaro', 'https://datatur.sectur.gob.mx/SitePages/VisitantesInternacionales.aspx', 'anual', 'sources.sectur.turismo_nacional_vs_internacional_queretaro', 'etl_listo', TRUE),
    (70, 'Datatur/Sectur — Derrama económica turística Querétaro', 'https://datatur.sectur.gob.mx/SitePages/VisitantesInternacionales.aspx', 'anual', 'sources.sectur.derrama_economica_turistica_queretaro', 'etl_listo', TRUE),
    (71, 'Datatur/Sectur — Ocupación hotelera Querétaro', 'https://datatur.sectur.gob.mx/SitePages/VisitantesInternacionales.aspx', 'anual', 'sources.sectur.ocupacion_hotelera_queretaro', 'etl_listo', TRUE),
    (72, 'Datatur/Sectur — Crecimiento de habitaciones ocupadas Querétaro', 'https://datatur.sectur.gob.mx/SitePages/VisitantesInternacionales.aspx', 'anual', 'sources.sectur.crecimiento_habitaciones_ocupadas_queretaro', 'etl_listo', TRUE),
    (73, 'AIQ — Pasajeros anuales Querétaro', 'https://aiq.com.mx/estadisticas.php', 'anual', 'sources.afac.pasajeros_anuales_aiq_queretaro', 'etl_listo', TRUE),
    (74, 'AIQ — Crecimiento anual de pasajeros Querétaro', 'https://aiq.com.mx/estadisticas.php', 'anual', 'sources.afac.crecimiento_anual_pasajeros_aiq_queretaro', 'etl_listo', TRUE),
    (75, 'AIQ — % vuelos nacionales / internacionales Querétaro', 'https://aiq.com.mx/estadisticas.php', 'anual', 'sources.afac.vuelos_nacionales_internacionales_aiq_queretaro', 'etl_listo', TRUE),
    (76, 'AIQ — Histórico de toneladas transportadas Querétaro', 'https://aiq.com.mx/estadisticas.php', 'anual', 'sources.afac.historico_toneladas_transportadas_aiq_queretaro', 'etl_listo', TRUE)
ON CONFLICT (id) DO UPDATE
SET
    nombre = EXCLUDED.nombre,
    url_referencia = EXCLUDED.url_referencia,
    periodicidad = EXCLUDED.periodicidad,
    modulo_etl = EXCLUDED.modulo_etl,
    estado = EXCLUDED.estado,
    activo = TRUE;

SELECT setval('public.fuentes_datos_id_seq', (SELECT MAX(id) FROM public.fuentes_datos));

INSERT INTO public.indicadores
    (clave, nombre, categoria, nivel_geografico, unidad, fuente_id, descripcion, tipo_grafica, activo)
VALUES
    ('banxico.pib_trimestral_mxn',        'PIB Nacional (MXN)',                           'economia',   'nacional', 'Millones de pesos', 1,  'PIB trimestral en MXN.', 'bar', TRUE),
    ('banxico.pib_trimestral_usd',        'PIB Nacional (USD)',                           'economia',   'nacional', 'Millones de dólares', 1, 'PIB trimestral en USD.', 'bar', TRUE),
    ('banxico.tipo_cambio_usd_mxn',       'Tipo de Cambio USD/MXN',                       'economia',   'nacional', 'Pesos por dólar', 2,     'Tipo de cambio FIX.', 'line', TRUE),
    ('banxico.inflacion_inpc_anual',      'Inflación INPC (variación anual)',             'economia',   'nacional', '%', 3,                    'Inflación anual INPC.', 'line', TRUE),
    ('inegi.poblacion_total_nacional',    'Población Total Nacional',                      'demografia', 'nacional', 'Personas', 4,            'Población total nacional.', 'bar', TRUE),
    ('inegi.grupos_edad_nacional',        'Distribución de la Población por Grupos de Edad','demografia','nacional', 'Personas', 5,            'Grupos de edad nacionales.', 'bar', TRUE),
    ('inegi.poblacion_sexo_nacional',     'Distribución de la Población por Sexo',         'demografia', 'nacional', 'Personas', 6,            'Población por sexo nacional.', 'bar', TRUE),
    ('inegi.pea_nacional',                'Población Económicamente Activa',               'economia',   'nacional', 'Personas', 7,            'PEA nacional.', 'bar', TRUE),
    ('inegi.ocupacion_sector_nacional',   'Población ocupada por sector',                  'economia',   'nacional', 'Personas', 8,            'Ocupación por sector.', 'bar', TRUE),
    ('worldbank.pib_anual_mxn',           'PIB Nacional (Total y Per cápita)',             'economia',   'nacional', 'MXN', 9,                 'PIB anual World Bank.', 'line', TRUE),
    ('imf.pib_proyeccion',                'Proyección del PIB Nacional',                    'economia',   'nacional', 'MXN', 10,                'Proyecciones FMI.', 'line', TRUE),
    ('se.ied_sector',                     'IED por Sector Económico',                       'economia',   'nacional', 'MDD', 11,                'IED por sector.', 'bar', TRUE),
    ('se.ied_pais',                       'IED por País de Origen',                         'economia',   'nacional', 'MDD', 12,                'IED por país.', 'pie', TRUE),
    ('wb.turismo_ingresos',               'Ingresos por turismo (WB)',                      'turismo',    'nacional', 'USD', 13,                'Ingresos por turismo WB.', 'line', TRUE),
    ('wb.turismo_ranking',                'Ranking de turismo mundial',                     'turismo',    'nacional', 'USD', 14,                'Ranking turismo WB.', 'bar', TRUE),
    ('inegi.balanza_visitantes',          'Balanza de visitantes',                          'turismo',    'nacional', 'Personas', 15,           'Balanza de visitantes.', 'line', TRUE),
    ('afac.mercado_aereo',                'Participación de mercado aéreo',                 'conectividad_aerea', 'nacional', '%', 16, 'Participación mercado aéreo.', 'pie', TRUE),
    ('se.anuncios_inversion',             'Anuncios de inversión combinados',               'economia',   'nacional', 'MDD', 17,                'Anuncios de inversión.', 'bar', TRUE),
    ('se.anuncios_base',                  'Anuncios de inversión base',                     'economia',   'nacional', 'MDD', 18,                'Anuncios base.', 'bar', TRUE),
    ('inegi.pib_sector',                  'PIB por sector económico',                       'economia',   'nacional', 'MXN', 19,                'PIB por sector.', 'pie', TRUE),
    ('inegi.balanza_comercial',           'Balanza comercial por producto',                 'economia',   'nacional', 'USD', 20,                'Balanza comercial.', 'bar', TRUE),
    ('afac.operaciones_aeroportuarias',   'Operaciones aeroportuarias',                     'conectividad_aerea', 'nacional', 'Operaciones', 21, 'Operaciones aeroportuarias.', 'bar', TRUE),
    ('inegi.actividad_hotelera',          'Actividad hotelera',                             'turismo',    'nacional', 'Cuartos', 22,            'Actividad hotelera.', 'bar', TRUE),
    ('se.ied_estados',                    'Flujo de IED por estado',                        'economia',   'nacional', 'MDD', 23,                'IED por estado.', 'bar', TRUE),
    ('inegi.estados_info',                'Población y PIB por estado',                     'demografia', 'estatal',  'Mixto', 24,              'PIB/Población/Extensión por estado.', 'bar', TRUE),
    ('inegi.demografia_estatal',          'Demografía estatal',                             'demografia', 'estatal',  'Personas', 25,           'Demografía estatal.', 'bar', TRUE),
    ('conapo.proyecciones_estatal',       'Proyecciones de población estatal',              'demografia', 'estatal',  'Personas', 26,           'Proyecciones CONAPO.', 'line', TRUE),
    ('inegi.itaee_estatal',               'Actividad económica (ITAEE) estatal',            'economia',   'estatal',  'Millones de pesos', 27,  'ITAEE estatal.', 'bar', TRUE),
    ('se.anuncios_estatal',               'Anuncios de inversión estatal',                  'economia',   'estatal',  'MDD', 28,                'Anuncios de inversión por estado.', 'bar', TRUE),
    ('sectur.hotelera_estatal',           'Actividad hotelera estatal',                     'turismo',    'estatal',  'Cuartos', 29,            'Actividad hotelera estatal.', 'bar', TRUE),
    ('sectur.llegada_turistas_estatal',   'Llegada de turistas por estado',                 'turismo',    'estatal',  'Personas', 30,           'Llegada de turistas estatal.', 'bar', TRUE),
    ('se.exportaciones_estatal',          'Exportaciones por estado',                        'economia',   'estatal',  'Millones USD', 31,       'Exportaciones por entidad federativa.', 'bar', TRUE),
    ('afac.aeropuertos_estatal',          'Aeropuertos por estado',                          'conectividad_aerea', 'estatal', 'Operaciones', 32, 'Operaciones por aeropuerto y estado.', 'bar', TRUE),
    ('conapo.municipios_poblacion',       'Población municipal por sexo',                    'demografia', 'municipal', 'Personas', 33,          'Población municipal total, hombres y mujeres (CONAPO).', 'bar', TRUE),
    ('conapo.municipios_piramide_edad',   'Distribución de la población municipal',          'demografia', 'municipal', 'Personas', 34,          'Distribución por grupos de edad y sexo en el municipio.', 'bar', TRUE),
    ('conapo.municipios_proyeccion',      'Proyección poblacional municipal',                'demografia', 'municipal', 'Personas', 35,          'Proyecciones a 5 años de población total, hombres y mujeres.', 'bar', TRUE),
    ('conapo.localidades_poblacion',      'Población por localidad',                         'demografia', 'localidad', 'Personas', 36,         'Población de localidades (total, mujeres y hombres).', 'bar', TRUE),
    ('conapo.localidades_piramide_edad',  'Distribución de la población por localidad',      'demografia', 'localidad', 'Personas', 37,         'Distribución por grupos de edad y sexo en la localidad.', 'bar', TRUE),
    ('inegi.ocupacion_restaurantes_hoteles_merida', 'Población ocupada en restaurantes y hoteles (Mérida)', 'economia', 'ciudad', 'Personas', 38, 'Población ocupada en servicios de alojamiento y restaurantes para Mérida, Yucatán.', 'line', TRUE),
    ('se.comercio_internacional_merida', 'Comercio internacional de Mérida', 'economia', 'ciudad', 'Millones USD', 39, 'Importaciones y exportaciones anuales de Mérida.', 'bar', TRUE),
    ('afac.conectividad_aerea_merida', 'Conectividad aérea de Mérida', 'conectividad_aerea', 'ciudad', 'Operaciones', 40, 'Total anual de operaciones aeroportuarias en Mérida.', 'line', TRUE),
    ('afac.conexiones_aereas_merida', 'Conexiones aéreas hacia Mérida', 'conectividad_aerea', 'ciudad', 'Vuelos', 41, 'Vuelos de llegada a Mérida por aeropuerto de origen.', 'bar', TRUE),
    ('sectur.oferta_servicios_turisticos_merida', 'Oferta de servicios turísticos en Mérida', 'turismo', 'ciudad', 'Mixto', 42, 'Servicios turísticos otorgados y ventas obtenidas por año.', 'bar', TRUE),
    ('sectur.ocupacion_hotelera_promedio_merida', 'Ocupación hotelera promedio en Mérida', 'turismo', 'ciudad', 'Porcentaje', 43, 'Porcentaje promedio anual de habitaciones ocupadas en establecimientos de hospedaje.', 'line', TRUE),
    ('sectur.llegada_visitantes_pernocta_merida', 'Llegada de visitantes con pernocta en Mérida', 'turismo', 'ciudad', 'Visitantes', 44, 'Visitantes con pernocta clasificados en nacionales e internacionales.', 'bar', TRUE),
    ('sectur.gasto_promedio_diario_pernocta_merida', 'Gasto promedio diario del visitante con pernocta en Mérida', 'turismo', 'ciudad', 'MXN', 45, 'Gasto monetario promedio diario de visitantes con pernocta.', 'line', TRUE),
    ('sectur.derrama_economica_pernocta_merida', 'Derrama económica estimada de visitantes con pernocta en Mérida', 'turismo', 'ciudad', 'Millones MXN', 46, 'Derrama económica anual estimada asociada a visitantes con pernocta.', 'bar', TRUE),
    ('sectur.ingreso_hotelero_merida', 'Ingreso hotelero en Mérida', 'turismo', 'ciudad', 'Millones MXN', 47, 'Ingreso hotelero anual estimado en establecimientos de hospedaje.', 'line', TRUE),
    ('sectur.establecimientos_servicios_turisticos_yucatan', 'Establecimientos de servicios turísticos en Yucatán', 'turismo', 'ciudad', 'Establecimientos', 48, 'Número anual estimado de establecimientos de servicios turísticos registrados en el estado.', 'bar', TRUE),
    ('se.comercio_internacional_monterrey', 'Comercio internacional de Monterrey', 'economia', 'ciudad', 'Millones USD', 49, 'Flujos anuales estimados de inversión/comercio internacional para Monterrey/Nuevo León.', 'bar', TRUE),
    ('se.exportaciones_importaciones_monterrey', 'Exportaciones e importaciones de Monterrey', 'economia', 'ciudad', 'Millones USD', 50, 'Serie anual de exportaciones e importaciones para Monterrey/Nuevo León.', 'bar', TRUE),
    ('afac.llegadas_pasajeros_monterrey', 'Llegadas de pasajeros de Monterrey', 'conectividad_aerea', 'ciudad', 'Pasajeros', 51, 'Llegadas anuales de pasajeros nacionales e internacionales en Monterrey.', 'bar', TRUE),
    ('sectur.visitantes_nacionales_extranjeros_monterrey', 'Visitantes nacionales y extranjeros en Monterrey', 'turismo', 'ciudad', 'Visitantes', 52, 'Visitantes anuales en Monterrey, desagregados en nacionales y extranjeros.', 'bar', TRUE),
    ('sectur.ocupacion_hotelera_monterrey', 'Ocupación hotelera en Monterrey', 'turismo', 'ciudad', 'Mixto', 53, 'Ocupación hotelera anual y cuartos disponibles/ocupados en Monterrey.', 'line', TRUE),
    ('inegi.pea_queretaro', 'Población económicamente activa (Querétaro)', 'economia', 'ciudad', 'Miles de personas', 54, 'PEA 15 años y más para la ZM/city Querétaro (serie referencial ENOE).', 'line', TRUE),
    ('inegi.tasa_participacion_laboral_queretaro', 'Tasa de participación laboral (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 55, 'Tasa de participación laboral de la población de 15 años y más para Querétaro (ENOE).', 'line', TRUE),
    ('inegi.tasa_desocupacion_queretaro', 'Tasa de desocupación (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 56, 'Tasa de desocupación de la PEA para Querétaro (ENOE).', 'line', TRUE),
    ('inegi.composicion_sectorial_empleo_queretaro', 'Composición sectorial del empleo (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 57, 'Distribución porcentual del empleo en sectores primario, secundario y terciario para Querétaro (ENOE).', 'bar', TRUE),
    ('inegi.pib_estatal_total_queretaro', 'PIB estatal total (Querétaro)', 'economia', 'ciudad', 'Millones de pesos', 58, 'PIB estatal total anual de Querétaro a precios corrientes.', 'line', TRUE),
    ('inegi.pib_per_capita_queretaro', 'PIB per cápita (Querétaro)', 'economia', 'ciudad', 'Pesos por habitante', 59, 'PIB per cápita anual de Querétaro a precios corrientes.', 'line', TRUE),
    ('inegi.pib_sector_queretaro', 'Distribución del PIB por sector (Querétaro)', 'economia', 'ciudad', 'Millones de pesos', 60, 'Distribución anual del PIB de Querétaro por sectores primario, secundario y terciario.', 'bar', TRUE),
    ('inegi.tasa_crecimiento_economico_queretaro', 'Tasa de crecimiento económico (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 61, 'Variación porcentual anual del PIB estatal de Querétaro.', 'line', TRUE),
    ('se.exportaciones_estatales_queretaro', 'Exportaciones estatales (Querétaro)', 'economia', 'ciudad', 'Millones USD', 62, 'Exportaciones estatales anuales de Querétaro.', 'line', TRUE),
    ('se.importaciones_estatales_queretaro', 'Importaciones estatales (Querétaro)', 'economia', 'ciudad', 'Millones USD', 63, 'Importaciones estatales anuales de Querétaro.', 'line', TRUE),
    ('se.comercio_internacional_neto_queretaro', 'Comercio internacional neto (Querétaro)', 'economia', 'ciudad', 'Millones USD', 64, 'Comercio internacional total anual de Querétaro (exportaciones + importaciones).', 'line', TRUE),
    ('se.balance_comercial_neto_queretaro', 'Balance comercial neto (Querétaro)', 'economia', 'ciudad', 'Millones USD', 65, 'Balance comercial anual de Querétaro (exportaciones - importaciones).', 'line', TRUE),
    ('se.ied_anual_queretaro', 'IED anual (Querétaro)', 'economia', 'ciudad', 'Millones USD', 66, 'Inversión extranjera directa anual de Querétaro.', 'line', TRUE),
    ('se.ied_municipio_queretaro', 'IED por municipio (Querétaro)', 'economia', 'ciudad', 'Millones USD', 67, 'IED anual de Querétaro desagregada por municipio.', 'bar', TRUE),
    ('inegi.llegada_total_turistas_queretaro', 'Llegada total de turistas (Querétaro)', 'economia', 'ciudad', 'Turistas', 68, 'Llegada total anual de turistas en Querétaro.', 'line', TRUE),
    ('sectur.turismo_nacional_vs_internacional_queretaro', 'Turismo nacional vs internacional (Querétaro)', 'economia', 'ciudad', 'Turistas', 69, 'Comparativo anual de turistas nacionales e internacionales en Querétaro.', 'line', TRUE),
    ('sectur.derrama_economica_turistica_queretaro', 'Derrama económica turística (Querétaro)', 'economia', 'ciudad', 'Millones MXN', 70, 'Derrama económica turística anual en Querétaro.', 'line', TRUE),
    ('sectur.ocupacion_hotelera_queretaro', 'Ocupación hotelera (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 71, 'Porcentaje anual de ocupación hotelera en Querétaro.', 'line', TRUE),
    ('sectur.crecimiento_habitaciones_ocupadas_queretaro', 'Crecimiento de habitaciones ocupadas (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 72, 'Variación porcentual anual de habitaciones ocupadas en Querétaro.', 'line', TRUE),
    ('afac.pasajeros_anuales_aiq_queretaro', 'Pasajeros anuales AIQ (Querétaro)', 'economia', 'ciudad', 'Pasajeros', 73, 'Pasajeros anuales del Aeropuerto Intercontinental de Querétaro.', 'line', TRUE),
    ('afac.crecimiento_anual_pasajeros_aiq_queretaro', 'Crecimiento anual de pasajeros (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 74, 'Variación porcentual anual de pasajeros del AIQ en Querétaro.', 'line', TRUE),
    ('afac.vuelos_nacionales_internacionales_aiq_queretaro', '% vuelos nacionales / internacionales (Querétaro)', 'economia', 'ciudad', 'Porcentaje', 75, 'Participación anual de vuelos nacionales e internacionales en el AIQ.', 'line', TRUE),
    ('afac.historico_toneladas_transportadas_aiq_queretaro', 'Histórico de toneladas transportadas (Querétaro)', 'economia', 'ciudad', 'Toneladas', 76, 'Toneladas transportadas anuales en el AIQ de Querétaro.', 'line', TRUE)
ON CONFLICT (clave) DO UPDATE
SET
    nombre = EXCLUDED.nombre,
    categoria = EXCLUDED.categoria,
    nivel_geografico = EXCLUDED.nivel_geografico,
    unidad = EXCLUDED.unidad,
    fuente_id = EXCLUDED.fuente_id,
    descripcion = EXCLUDED.descripcion,
    tipo_grafica = EXCLUDED.tipo_grafica,
    activo = TRUE;
